name: WP Decoupled Preview Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint & Test
    env:
      DB_USER: root
      DB_PASSWORD: ''
      DB_HOST: localhost
    steps:
      - uses: actions/checkout@v2
      - name: Install Composer dependencies
        run: composer install
      - name: Install WP Unit tests
        run: |
          php -v
          mysqladmin -V
          sudo /etc/init.d/mysql start
          composer test:install
      - name: Run linter
        run: composer lint
      - name: Run tests
        run: composer test